### PR TITLE
 Deprecating python 3.6

### PR DESCRIPTION
**Pull request by atalman**
This is to deprecate python 3.6

### CODE REVIEW

**Comment by jeffdaily** [comment]
Do not merge this.  We must update our ROCm CI image to use python 3.7 prior to disabling the only Jenkins CI job we currently have for ROCm.

**Comment by suo** [comment]
@jeffdaily we can hold on this. How soon can we update the ROCm CI image?

**Comment by atalman** [comment]
@jeffdaily The image pytorch/pytorch-linux-bionic-rocm4.5-py3.7 is available now. Can we use it instead of pytorch-linux-bionic-rocm4.3.1-py3.6 ? Please review this PR

**Comment by jeffdaily** [comment]
Will merge #120 instead of this PR since it also updates the image tag to the latest.

**Pull request closed without merging**
